# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FF_T8VgpcZplMkx5YHUnxOpN5mphz545
"""

!pip install transformers accelerate torch

!pip install huggingface_hub

!pip install -q kaleido

from huggingface_hub import snapshot_download

snapshot_download(
    repo_id="Qwen/Qwen2.5-3B-Instruct",
    local_dir="qwen_model",
    local_dir_use_symlinks=False
)

import plotly.graph_objects as go

def plot_roadmap(roadmap, title="Learning Roadmap"):
    """
    roadmap: dict
        مثال:
        {
            "Phase 1": ["Task 1", "Task 2"],
            "Phase 2": ["Task 1", "Task 2"]
        }
    title: str
        عنوان الصورة
    """
    phases = list(roadmap.keys())
    colors = ["#636EFA", "#EF553B", "#00CC96", "#AB63FA", "#FFA15A", "#19D3F3"]

    fig = go.Figure()

    for i, phase in enumerate(phases):
        tasks = roadmap[phase]
        fig.add_trace(go.Bar(
            y=[phase]*len(tasks),
            x=[1]*len(tasks),
            orientation='h',
            text=tasks,
            textposition='inside',
            marker_color=colors[i % len(colors)],
            name=phase
        ))

    fig.update_layout(
        title=title,
        barmode='stack',
        xaxis=dict(showticklabels=False),
        yaxis=dict(autorange="reversed"),
        height=400 + 50*len(phases),
        showlegend=False
    )

    fig.show()


    fig.write_image("roadmap.png")  # PNG
    #fig.write_image("roadmap.pdf")  # PDF

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

model_name = "Qwen/Qwen2.5-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto",
    trust_remote_code=True
)

def generate_roadmap(user_input):
    prompt = f"""
You are an expert learning planner.

The user wants a roadmap.

User request:
"{user_input}"

Create a clear and structured roadmap.
Divide it into phases or months.
Use simple bullet points.
"""

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=600,
        temperature=0.7
    )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)


# ======================
# User Input
# ======================

user_input = input("اكتب اسم التراك أو طلبك: ")
roadmap = generate_roadmap(user_input)

print("\n========== ROADMAP ==========\n")
print(roadmap)

import re

def parse_roadmap_string(roadmap_str):
    parsed_roadmap = {}
    current_phase = None

    lines = roadmap_str.split('\n')

    # Skip introductory text until the first phase header is found
    roadmap_content_started = False
    for line in lines:
        if line.strip().startswith('###'):
            roadmap_content_started = True
            break

    if not roadmap_content_started:
        return {} # Return empty if no structured roadmap content found

    # Process lines from where the structured roadmap begins
    for line in lines:
        line_trimmed = line.strip()
        if not line_trimmed:
            continue

        if line_trimmed.startswith('###'):
            # This is a new phase header
            phase_name_match = re.match(r'###\s*(.*)', line_trimmed)
            if phase_name_match:
                current_phase = phase_name_match.group(1).strip()
                parsed_roadmap[current_phase] = []
        elif current_phase is not None:
            # This is a task bullet point (can be indented)
            bullet_match = re.match(r'^\s*[-*]\s*(.*)', line)
            if bullet_match:
                task = bullet_match.group(1).strip()
                # Remove markdown bolding if present
                task = re.sub(r'\*\*([^*]+)\*\*', r'\1', task)
                if task:
                    parsed_roadmap[current_phase].append(task)

    # Filter out any phases that ended up empty
    parsed_roadmap = {k: v for k, v in parsed_roadmap.items() if v}
    return parsed_roadmap

# Parse the roadmap string into a dictionary
parsed_roadmap_dict = parse_roadmap_string(roadmap)

# Call plot_roadmap with the parsed dictionary
plot_roadmap(parsed_roadmap_dict, title="Learning Roadmap")